version: '3'
services:
  db: 
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=php_docker
      - MYSQL_USER=php_docker
      - MYSQL_PASSWORD=password   # move this to .env in production
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
    networks:
      - laravel_net

  www:
    image: php:apache
    volumes:
      - "./:/var/www/html"
    depends_on:
      - db
    networks:
      - laravel_net
    # No ports section → Coolify will assign a domain

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    depends_on:
      - db
    networks:
      - laravel_net
    # No ports section → Coolify will assign a domain

networks:
  laravel_net:
    driver: bridge
