version: '3'
services:
  db: 
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=php_docker
      - MYSQL_USER=php_docker
      - MYSQL_PASSWORD=password # should be stored in .env
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./db:/docker-entrypoint-initdb.d"

  www:
    image: php:apache
    volumes:
      - "./:/var/www/html"
    ports:
      - "8080:80"   # changed from 80:80 to 8080:80
      - "8443:443"  # optional, avoid clashing with system 443

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
