version: '3'
services:
  db:
    image: mysql:latest
    container_name: simple_php_db
    environment:
      - MYSQL_DATABASE=php_docker
      - MYSQL_USER=php_docker
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
    networks:
      - simple_net

  www:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simple_php_www
    volumes:
      - "./:/var/www/html"
    depends_on:
      - db
    networks:
      - simple_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: simple_php_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: php_docker
      PMA_PASSWORD: password
    depends_on:
      - db
    networks:
      - simple_net

networks:
  simple_net:
    driver: bridge
