version: '3'
services:
  db:
    image: mysql:latest
    container_name: laravel_db
    environment:
      - MYSQL_DATABASE=php_docker
      - MYSQL_USER=php_docker
      - MYSQL_PASSWORD=password   # move to .env in production
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
    networks:
      - laravel_net

  www:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_www
    volumes:
      - "./:/var/www/html"
      - "./docker/apache.conf:/etc/apache2/sites-available/000-default.conf:ro"
    depends_on:
      - db
    networks:
      - laravel_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: php_docker
      PMA_PASSWORD: password
      PMA_UPLOAD_MAX_FILESIZE: 64M
      PMA_MAX_EXECUTION_TIME: 600
    depends_on:
      - db
    networks:
      - laravel_net

networks:
  laravel_net:
    driver: bridge
