[phases.setup]
nixPkgs = [
  "php83",
  "php83Extensions.curl",
  "php83Extensions.mbstring",
  "php83Extensions.pdo_mysql",
  "php83Extensions.tokenizer",
  "php83Extensions.xml",
  "php83Extensions.fileinfo",
  "composer",
  "nodejs_20"
]

[phases.install]
cmds = [
  "cp .env.example .env || true",
  "chmod 0644 .env",
  "composer install --no-dev --optimize-autoloader",
  "chmod -R 775 storage bootstrap/cache"
]

[phases.build]
cmds = [
  "npm install && npm run build || true"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT:-8080}"
